sudo: false
language: python
python:
  - "2.7"
env:
  - PROF=deb7
  - PROF=deb8
  - PROF=deb9
addons:
  apt:
    packages:
    - protobuf-compiler
    - libprotobuf-dev
install:
  - pip install -r requirements-${PROF}.txt
  - python setup.py build_protobuf -i
  - python setup.py build_ext -i
script: TZ=US/Eastern trial carchive
