name: carchivetools

on: [push, pull_request]

jobs:
  native:
    name: ${{ matrix.os }}/${{ matrix.py }}/${{ matrix.prof }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
           - os: ubuntu-latest
             py: 2.7
             prof: latest
             # doctests and others aren't ported
             test: false

           - os: ubuntu-latest
             py: 3.7
             prof: latest
             test: true

           - os: ubuntu-latest
             py: 3.8
             prof: latest
             test: true

           - os: ubuntu-latest
             py: 3.9
             prof: latest
             # some bizarre in carchive.test.test_util.TestBLP.test_short
             test: false

    steps:
    - uses: actions/checkout@v2

    - name: "apt-get install"
      run: |
        sudo apt-get update
        sudo apt-get -y install protobuf-compiler libprotobuf-dev

    - name: Setup native python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.py }}

    - name: Build
      run: |
        python -m pip install -r requirements-${{ matrix.prof }}.txt
        python setup.py build_protobuf -i
        python setup.py build_ext -i

    - name: Test
      if: matrix.test
      run: |
        which trial
        PYTHONPATH=$PWD TZ=US/Eastern trial carchive
